// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var Sort$Algorithms = require("./Sort.bs.js");

console.log(Sort$Algorithms.quickSort(/* array */[
          4,
          1,
          3,
          5,
          2,
          6
        ]));

/*  Not a pure module */
