// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var Caml_obj = require("bs-platform/lib/js/caml_obj.js");

function binarySearch(item, arr) {
  var len = arr.length;
  if (len !== 1) {
    return /* None */0;
  } else {
    var x = arr[0];
    var match = Caml_obj.caml_equal(x, item);
    if (match) {
      return /* Some */[0];
    } else {
      return /* None */0;
    }
  }
}

exports.binarySearch = binarySearch;
/* No side effect */
