// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var Random = require("bs-platform/lib/js/random.js");
var Caml_obj = require("bs-platform/lib/js/caml_obj.js");
var Belt_Array = require("bs-platform/lib/js/belt_Array.js");
var Caml_array = require("bs-platform/lib/js/caml_array.js");
var Caml_builtin_exceptions = require("bs-platform/lib/js/caml_builtin_exceptions.js");

function remove(arr, i) {
  var part1 = $$Array.sub(arr, 0, i);
  var len = (arr.length - i | 0) - 1 | 0;
  var part2 = $$Array.sub(arr, i + 1 | 0, len);
  return $$Array.append(part1, part2);
}

var ArrayUtil = /* module */[/* remove */remove];

function findSmallest_(arr, _i, length, _minVal, _minIndex) {
  while(true) {
    var minIndex = _minIndex;
    var minVal = _minVal;
    var i = _i;
    if (i >= length) {
      return /* tuple */[
              minVal,
              minIndex
            ];
    } else {
      var value = Caml_array.caml_array_get(arr, i);
      var match = Caml_obj.caml_lessthan(value, minVal) ? /* tuple */[
          value,
          i
        ] : /* tuple */[
          minVal,
          minIndex
        ];
      _minIndex = match[1];
      _minVal = match[0];
      _i = i + 1 | 0;
      continue ;
    }
  };
}

function findSmallest(arr) {
  var len = arr.length;
  if (len !== 1) {
    if (len !== 0) {
      return findSmallest_(arr, 1, arr.length, Caml_array.caml_array_get(arr, 0), 0);
    } else {
      throw Caml_builtin_exceptions.not_found;
    }
  } else {
    var x = arr[0];
    return /* tuple */[
            x,
            0
          ];
  }
}

function sort(_arr, _acc) {
  while(true) {
    var acc = _acc;
    var arr = _arr;
    if (arr.length !== 0) {
      var match = findSmallest(arr);
      var newArr = remove(arr, match[1]);
      var newAcc = $$Array.append(acc, /* array */[match[0]]);
      _acc = newAcc;
      _arr = newArr;
      continue ;
    } else {
      return acc;
    }
  };
}

var Selection = /* module */[
  /* findSmallest_ */findSmallest_,
  /* findSmallest */findSmallest,
  /* sort */sort
];

function selectionSort(arr) {
  var len = arr.length;
  if (len !== 1) {
    if (len !== 0) {
      return sort(arr, /* array */[]);
    } else {
      return /* array */[];
    }
  } else {
    return /* array */[arr[0]];
  }
}

function naiveQuickSort(arr) {
  var len = arr.length;
  if (len >= 3) {
    var index = Random.$$int(arr.length);
    var pivot = Caml_array.caml_array_get(arr, index);
    return $$Array.concat(/* :: */[
                naiveQuickSort(Belt_Array.keep(arr, (function (v) {
                            return Caml_obj.caml_lessthan(v, pivot);
                          }))),
                /* :: */[
                  Belt_Array.keep(arr, (function (v) {
                          return Caml_obj.caml_equal(v, pivot);
                        })),
                  /* :: */[
                    naiveQuickSort(Belt_Array.keep(arr, (function (v) {
                                return Caml_obj.caml_greaterthan(v, pivot);
                              }))),
                    /* [] */0
                  ]
                ]
              ]);
  } else {
    switch (len) {
      case 0 : 
      case 1 : 
          return arr;
      case 2 : 
          var x = arr[0];
          var y = arr[1];
          var match = Caml_obj.caml_lessequal(x, y);
          if (match) {
            return arr;
          } else {
            return /* array */[
                    y,
                    x
                  ];
          }
      
    }
  }
}

function swap(arr, i, j) {
  var temp = Caml_array.caml_array_get(arr, i);
  Caml_array.caml_array_set(arr, i, Caml_array.caml_array_get(arr, j));
  return Caml_array.caml_array_set(arr, j, temp);
}

function partition(arr, low, high) {
  var pivotValue = Caml_array.caml_array_get(arr, high);
  var i = low - 1 | 0;
  for(var j = low ,j_finish = high - 1 | 0; j <= j_finish; ++j){
    if (Caml_obj.caml_lessequal(Caml_array.caml_array_get(arr, j), pivotValue)) {
      i = i + 1 | 0;
      swap(arr, i, j);
    }
    
  }
  swap(arr, i + 1 | 0, high);
  return i + 1 | 0;
}

function partitionRandom(arr, low, high) {
  var i = Random.$$int(arr.length);
  swap(arr, i, high);
  return partition(arr, low, high);
}

function sort$1(arr, low, high) {
  var low$1 = low;
  while(low$1 < high) {
    var pivotIndex = partition(arr, low$1, high);
    sort$1(arr, low$1, pivotIndex - 1 | 0);
    low$1 = pivotIndex + 1 | 0;
  };
  return /* () */0;
}

var QuickSort = /* module */[
  /* swap */swap,
  /* partition */partition,
  /* partitionRandom */partitionRandom,
  /* sort */sort$1
];

function quickSort(arr) {
  sort$1(arr, 0, arr.length - 1 | 0);
  return arr;
}

exports.ArrayUtil = ArrayUtil;
exports.Selection = Selection;
exports.selectionSort = selectionSort;
exports.naiveQuickSort = naiveQuickSort;
exports.QuickSort = QuickSort;
exports.quickSort = quickSort;
/* No side effect */
