// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/src/jest.js");
var Search$Algorithms = require("../src/Search.bs.js");

describe("Binary search", (function () {
        Jest.test("0 elements", (function () {
                return Jest.Expect[/* toBe */2](/* None */0, Jest.Expect[/* expect */0](Search$Algorithms.binarySearch(3, /* array */[])));
              }));
        Jest.test("1 element, not found", (function () {
                return Jest.Expect[/* toBe */2](/* None */0, Jest.Expect[/* expect */0](Search$Algorithms.binarySearch(3, /* array */[22])));
              }));
        return Jest.test("1 element, found", (function () {
                      return Jest.Expect[/* toEqual */12](/* Some */[0], Jest.Expect[/* expect */0](Search$Algorithms.binarySearch(22, /* array */[22])));
                    }));
      }));

var binarySearch = Search$Algorithms.binarySearch;

exports.binarySearch = binarySearch;
/*  Not a pure module */
