// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/src/jest.js");
var Caml_obj = require("bs-platform/lib/js/caml_obj.js");
var Belt_Array = require("bs-platform/lib/js/belt_Array.js");
var Belt_SortArray = require("bs-platform/lib/js/belt_SortArray.js");
var Sort$Algorithms = require("../src/Sort.bs.js");

describe("Selection sort", (function () {
        Jest.test("0 elements", (function () {
                return Jest.Expect[/* toEqual */12](/* array */[], Jest.Expect[/* expect */0](Sort$Algorithms.selectionSort(/* array */[])));
              }));
        Jest.test("1 element", (function () {
                return Jest.Expect[/* toEqual */12](/* array */[55], Jest.Expect[/* expect */0](Sort$Algorithms.selectionSort(/* array */[55])));
              }));
        Jest.test("5 elements", (function () {
                return Jest.Expect[/* toEqual */12](Belt_Array.range(1, 5), Jest.Expect[/* expect */0](Sort$Algorithms.selectionSort(/* array */[
                                    4,
                                    3,
                                    1,
                                    5,
                                    2
                                  ])));
              }));
        return Jest.test("Many elements", (function () {
                      var result = Sort$Algorithms.selectionSort(Belt_Array.shuffle(Belt_Array.range(1, 200)));
                      return Jest.Expect[/* toBe */2](true, Jest.Expect[/* expect */0](Belt_SortArray.isSorted(result, Caml_obj.caml_compare)));
                    }));
      }));

var selectionSort = Sort$Algorithms.selectionSort;

exports.selectionSort = selectionSort;
/*  Not a pure module */
